### ISSUE TITLE
Doesn't work on pr from forks

### ISSUE THREAD

**Issue by crondaemon** [superbrothers/close-pull-request#4]
Hi
I've investigated a bit and it looks like your action doesn't work with forks since the fork user cannot access the github token. Can you confirm this? Is there a way to circumvent this issue?

**Comment by Lekensteyn** [comment]
Is this accurate? Doesn't this require a secret token to be created on the main repo?

See also "About the GITHUB_TOKEN secret" in https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by crondaemon** [comment]
When a fork opens a pull request on the upstream repo, the action fired runs on the forked repo, not the upstream. The forked repo doesn't have access to the access tokens created on the upstream repo. As the owner of the forked repo can't merge the PR on the upstream, as their actions can't.

**Comment by superbrothers** [comment]
Thanks for reporting. I'll check it out.

**Comment by superbrothers** [comment]
>  The forked repo doesn't have access to the access tokens created on the upstream repo. 

This is mostly correct. It turns out that `GITHUB_TOKEN` can only work on pull requests from a branch of the same repository, since it only gives "read" permissions to GITHUB_TOKEN in a forked repository.

- https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token

This is the same restriction in [actions/labeler](https://github.com/actions/labeler).

> Note that only pull requests being opened from the same repository can be labeled. This action will not currently work for pull requests from forks -- like is common in open source projects -- because the token for forked pull request workflows does not have write permissions.

Unfortunately, there seems to be no way around this restriction at the moment.
